# .github/dependabot.yml
version: 2

updates:
  # 1) Rust / Cargo (workspace)
  - package-ecosystem: "cargo"
    directories:
      - "/"            # корень с workspace Cargo.toml (оставь только реально существующие)
      - "/api-server"
      - "/client"
      - "/crates/*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"      # для Cargo допустимо только: auto | lockfile-only
    cooldown:
      default-days: 1
      semver-minor-days: 2
      semver-patch-days: 2
    commit-message:
      prefix: "deps(cargo)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    groups:
      cargo-minor-patch:
        applies-to: "version-updates"
        update-types: ["minor", "patch"]
        patterns: ["*"]

  # 2) GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:10"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(ci)"

  # 3) Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:20"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(docker)"
