[package]
name = "telegram-webapp-sdk"
version = "0.1.0"
edition = "2024"
description = "Telegram WebApp SDK for Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/RAprogramm/telegram-webapp-sdk"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6"
serde_urlencoded = "0.7"
once_cell = "1.21"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
  "Event",
  "Window",
  "Document",
  "Element",
  "HtmlElement",
  "console",
  "Navigator",
  "Geolocation",
  "Location",
  "CssStyleDeclaration",
] }
hmac-sha256 = "1.1"
hex = "0.4"
percent-encoding = "2.3"
urlencoding = "2.1"

[workspace]
members = ["demo"]
