coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    project:
      default:
        target: 95%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 90%
        threshold: 2%
        informational: false

comment:
  layout: "header,diff,flags,components,files,footer"
  behavior: default
  require_head: true

ignore:
  - "benches/**/*"
  - "tests/**/*"
  - "target/**/*"
  - ".github/**/*"
  - "src/leptos.rs"
  - "src/leptos/**/*"
  - "src/yew.rs"
  - "src/yew/**/*"
  - "src/api/**/*"
  - "src/webapp.rs"
  - "src/logger.rs"
  - "src/pages.rs"
  - "src/router.rs"

github_checks:
  annotations: true
