# Configuration for cargo-deny to enforce dependency policies.
# Keep the configuration compact; split responsibilities into focused sections.

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "simplest-path"

[licenses]
allow = [
    "0BSD",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-1-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
confidence-threshold = 0.8

[sources]
unknown-git = "deny"
unknown-registry = "deny"
