[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
  "Window",
  "Document",
  "HtmlElement",
  "History",
  "Location",
  "Event",
  "EventTarget",
  "CustomEvent",
  "CustomEventInit",
  "console",
  "Text",
] }
telegram-webapp-sdk = { path = "../", features = ["mock"] }

[[bin]]
name = "demo"
path = "src/main.rs"
test = false
bench = false
